### ISSUE TITLE
”与“之后第一个”奥“没有花纹

### ISSUE THREAD

**Issue by MeishanWu** [ddiu8081/oreooo#10]
请问是故意这样的吗？
![tim 20190307164742](https://user-images.githubusercontent.com/22040444/53994822-eafc9680-40f8-11e9-8771-38c6a7755cb3.png)

**Comment by ddiu8081** [comment]
是的😐 设定是花纹在下面

**Comment by MeishanWu** [comment]
不好意思。。。
