### ISSUE TITLE
Hi diu! I found a small problem in `generate` button.

### ISSUE THREAD

**Issue by daluozha** [ddiu8081/oreooo#17]
I clicked the `generate` button when the oreoList is empty, the loading animation came out. But after animation there was no result on the page.
I think it's better that the button is disable when empty, or  generate the result by using the input placeholder as default.
Forgive my bad grammar. I am just trying to discuss questions by using English 😆

**Comment by ddiu8081** [comment]
Thanks for finding the problem. 
I prefer the first option, just adding a validation to the onClickEvent and then adding a disabled state CSS to the button.

Feel free to pr if interested 😀

**Comment by daluozha** [comment]
> Thanks for finding the problem. I prefer the first option, just adding a validation to the onClickEvent and then adding a disabled state CSS to the button.
> 
> Feel free to pr if interested 😀

Of course I would like to fix it. I will PR soon 😺
