### ISSUE TITLE
Can't save image on mobile devices / 保存图片功能无法在移动端使用

### ISSUE THREAD

**Issue by ddiu8081** [ddiu8081/oreooo#2]
目前的保存图片用到了 a 标签的 download 属性，在移动端的兼容性很差。
在不涉及后端的情况下，有没有比较完备的解决方案？

**Comment by samondlee** [comment]
@mygoare

**Comment by mygoare** [comment]
> @mygoare

大概搜索了一下，没有找到比较好的解决方案，移动上主要是 iphone ios 对download attribute支持不好

**Comment by samondlee** [comment]
> > @mygoare
> 
> 大概搜索了一下，没有找到比较好的解决方案，移动上主要是 iphone ios 对download attribute支持不好

哈哈哈这个沙雕奥利奥好好玩！
