### ISSUE TITLE
英文状态下没有换行

### ISSUE THREAD

**Issue by BobLiu0518** [ddiu8081/oreooo#3]
![image](https://user-images.githubusercontent.com/24805093/50897994-bba71180-1448-11e9-961b-0b3271d26b78.png)
![image](https://user-images.githubusercontent.com/24805093/50898019-cfeb0e80-1448-11e9-84e4-73e9cdfe2ee6.png)
如图

**Comment by ddiu8081** [comment]
感谢，已修复
